# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mysdb/myGitLib/test/myGitHub/ui_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mysdb/myGitLib/test/myGitHub/ui_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mysdb/myGitLib/test/myGitHub/ui_cpp/CMakeFiles /mysdb/myGitLib/test/myGitHub/ui_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mysdb/myGitLib/test/myGitHub/ui_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/build
.PHONY : src/fast

src/amoled.o: src/amoled.c.o
.PHONY : src/amoled.o

# target to build an object file
src/amoled.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/amoled.c.o
.PHONY : src/amoled.c.o

src/amoled.i: src/amoled.c.i
.PHONY : src/amoled.i

# target to preprocess a source file
src/amoled.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/amoled.c.i
.PHONY : src/amoled.c.i

src/amoled.s: src/amoled.c.s
.PHONY : src/amoled.s

# target to generate assembly for a file
src/amoled.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/amoled.c.s
.PHONY : src/amoled.c.s

src/bmp.o: src/bmp.c.o
.PHONY : src/bmp.o

# target to build an object file
src/bmp.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/bmp.c.o
.PHONY : src/bmp.c.o

src/bmp.i: src/bmp.c.i
.PHONY : src/bmp.i

# target to preprocess a source file
src/bmp.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/bmp.c.i
.PHONY : src/bmp.c.i

src/bmp.s: src/bmp.c.s
.PHONY : src/bmp.s

# target to generate assembly for a file
src/bmp.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/bmp.c.s
.PHONY : src/bmp.c.s

src/gbk2312.o: src/gbk2312.c.o
.PHONY : src/gbk2312.o

# target to build an object file
src/gbk2312.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/gbk2312.c.o
.PHONY : src/gbk2312.c.o

src/gbk2312.i: src/gbk2312.c.i
.PHONY : src/gbk2312.i

# target to preprocess a source file
src/gbk2312.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/gbk2312.c.i
.PHONY : src/gbk2312.c.i

src/gbk2312.s: src/gbk2312.c.s
.PHONY : src/gbk2312.s

# target to generate assembly for a file
src/gbk2312.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/gbk2312.c.s
.PHONY : src/gbk2312.c.s

src/jpeg.o: src/jpeg.c.o
.PHONY : src/jpeg.o

# target to build an object file
src/jpeg.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/jpeg.c.o
.PHONY : src/jpeg.c.o

src/jpeg.i: src/jpeg.c.i
.PHONY : src/jpeg.i

# target to preprocess a source file
src/jpeg.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/jpeg.c.i
.PHONY : src/jpeg.c.i

src/jpeg.s: src/jpeg.c.s
.PHONY : src/jpeg.s

# target to generate assembly for a file
src/jpeg.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/jpeg.c.s
.PHONY : src/jpeg.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.o
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.i
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.s
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/touch.o: src/touch.c.o
.PHONY : src/touch.o

# target to build an object file
src/touch.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/touch.c.o
.PHONY : src/touch.c.o

src/touch.i: src/touch.c.i
.PHONY : src/touch.i

# target to preprocess a source file
src/touch.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/touch.c.i
.PHONY : src/touch.c.i

src/touch.s: src/touch.c.s
.PHONY : src/touch.s

# target to generate assembly for a file
src/touch.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/touch.c.s
.PHONY : src/touch.c.s

src/ttfType.o: src/ttfType.c.o
.PHONY : src/ttfType.o

# target to build an object file
src/ttfType.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/ttfType.c.o
.PHONY : src/ttfType.c.o

src/ttfType.i: src/ttfType.c.i
.PHONY : src/ttfType.i

# target to preprocess a source file
src/ttfType.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/ttfType.c.i
.PHONY : src/ttfType.c.i

src/ttfType.s: src/ttfType.c.s
.PHONY : src/ttfType.s

# target to generate assembly for a file
src/ttfType.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/ttfType.c.s
.PHONY : src/ttfType.c.s

src/view.o: src/view.cpp.o
.PHONY : src/view.o

# target to build an object file
src/view.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/view.cpp.o
.PHONY : src/view.cpp.o

src/view.i: src/view.cpp.i
.PHONY : src/view.i

# target to preprocess a source file
src/view.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/view.cpp.i
.PHONY : src/view.cpp.i

src/view.s: src/view.cpp.s
.PHONY : src/view.s

# target to generate assembly for a file
src/view.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/view.cpp.s
.PHONY : src/view.cpp.s

src/viewPen.o: src/viewPen.cpp.o
.PHONY : src/viewPen.o

# target to build an object file
src/viewPen.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewPen.cpp.o
.PHONY : src/viewPen.cpp.o

src/viewPen.i: src/viewPen.cpp.i
.PHONY : src/viewPen.i

# target to preprocess a source file
src/viewPen.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewPen.cpp.i
.PHONY : src/viewPen.cpp.i

src/viewPen.s: src/viewPen.cpp.s
.PHONY : src/viewPen.s

# target to generate assembly for a file
src/viewPen.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewPen.cpp.s
.PHONY : src/viewPen.cpp.s

src/viewPicture.o: src/viewPicture.cpp.o
.PHONY : src/viewPicture.o

# target to build an object file
src/viewPicture.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewPicture.cpp.o
.PHONY : src/viewPicture.cpp.o

src/viewPicture.i: src/viewPicture.cpp.i
.PHONY : src/viewPicture.i

# target to preprocess a source file
src/viewPicture.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewPicture.cpp.i
.PHONY : src/viewPicture.cpp.i

src/viewPicture.s: src/viewPicture.cpp.s
.PHONY : src/viewPicture.s

# target to generate assembly for a file
src/viewPicture.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewPicture.cpp.s
.PHONY : src/viewPicture.cpp.s

src/viewShape.o: src/viewShape.cpp.o
.PHONY : src/viewShape.o

# target to build an object file
src/viewShape.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewShape.cpp.o
.PHONY : src/viewShape.cpp.o

src/viewShape.i: src/viewShape.cpp.i
.PHONY : src/viewShape.i

# target to preprocess a source file
src/viewShape.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewShape.cpp.i
.PHONY : src/viewShape.cpp.i

src/viewShape.s: src/viewShape.cpp.s
.PHONY : src/viewShape.s

# target to generate assembly for a file
src/viewShape.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/viewShape.cpp.s
.PHONY : src/viewShape.cpp.s

src/wlan.o: src/wlan.c.o
.PHONY : src/wlan.o

# target to build an object file
src/wlan.c.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/wlan.c.o
.PHONY : src/wlan.c.o

src/wlan.i: src/wlan.c.i
.PHONY : src/wlan.i

# target to preprocess a source file
src/wlan.c.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/wlan.c.i
.PHONY : src/wlan.c.i

src/wlan.s: src/wlan.c.s
.PHONY : src/wlan.s

# target to generate assembly for a file
src/wlan.c.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/wlan.c.s
.PHONY : src/wlan.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... app"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src"
	@echo "... src/amoled.o"
	@echo "... src/amoled.i"
	@echo "... src/amoled.s"
	@echo "... src/bmp.o"
	@echo "... src/bmp.i"
	@echo "... src/bmp.s"
	@echo "... src/gbk2312.o"
	@echo "... src/gbk2312.i"
	@echo "... src/gbk2312.s"
	@echo "... src/jpeg.o"
	@echo "... src/jpeg.i"
	@echo "... src/jpeg.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/touch.o"
	@echo "... src/touch.i"
	@echo "... src/touch.s"
	@echo "... src/ttfType.o"
	@echo "... src/ttfType.i"
	@echo "... src/ttfType.s"
	@echo "... src/view.o"
	@echo "... src/view.i"
	@echo "... src/view.s"
	@echo "... src/viewPen.o"
	@echo "... src/viewPen.i"
	@echo "... src/viewPen.s"
	@echo "... src/viewPicture.o"
	@echo "... src/viewPicture.i"
	@echo "... src/viewPicture.s"
	@echo "... src/viewShape.o"
	@echo "... src/viewShape.i"
	@echo "... src/viewShape.s"
	@echo "... src/wlan.o"
	@echo "... src/wlan.i"
	@echo "... src/wlan.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

